# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate]

# Site settings
title: dutton.me.uk - Software Engineering, Photography, Travel, Stuffâ€¦
description: > # this means to ignore newlines until "baseurl:"
  #words
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dutton.me.uk" # the base hostname & protocol for your site
twitter_username: dutts303
github_username:  dutts
permalink:    /:year/:month/:day/:title/

paginate: 5

# Build settings
markdown: kramdown
